### PR TITLE
Update Falcon::Server.new call with keyword args

### PR DESCRIPTION
**Pull request by parndt**
## Types of Changes

- [x] Bug fix.
- [ ] New feature.
- [ ] Performance improvement.

## Testing

- [ ] I added new tests for my changes.
- [x] I ran all the tests locally.

This handles the change to this API in the commit to async-http:
socketry/async-http@3e967d4ff729bb4f02587d3e5784fd5cf4e37c26

### CODE REVIEW

**Comment by deepj** [comment]
@ioquatix Hello, is it possible to merge it and release a new version. Without this fix is not possible run tests with falcon on Ruby 3.0 :)

**Comment by ioquatix** [comment]
Yes, I thought I already handled this, that's odd. Thanks for the PR, I'll check what's going on.

**Comment by ioquatix** [comment]
Oh.... this is something I did not fix.

**Comment by ioquatix** [comment]
Okay, released.

**Pull request merged**
